### ISSUE TITLE
can not import ova file into vmware esxi

### ISSUE THREAD

**Issue by p1plp1** [librenms/packer-builds#12]
impossible to import librenms into vmware esxi tested on 5.5 6.0 6.5,
editing ide controller section in ovf file doesnt solves this problem, vmdk file looks corrupted for esxi.

**Comment by JumpMaster** [comment]
The following OVF worked for me.  I then imported the ovf and vmdk ignoring the mf file.

Or for better formatting via pastebin:
https://pastebin.com/r3wCx8v1

`<?xml version="1.0"?>
<Envelope ovf:version="1.0" xml:lang="en-US" xmlns="http://schemas.dmtf.org/ovf/envelope/1" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:vbox="http://www.virtualbox.org/ovf/machine">
  <References>
    <File ovf:id="file1" ovf:href="librenms-ubuntu-18.04-amd64-disk001.vmdk"/>
  </References>
  <DiskSection>
    <Info>List of the virtual disks used in the package</Info>
    <Disk ovf:capacity="42949672960" ovf:diskId="vmdisk1" ovf:fileRef="file1" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized" vbox:uuid="c35661a3-9696-4a98-a1a2-d7407388171e"/>
  </DiskSection>
  <NetworkSection>
    <Info>Logical networks used in the package</Info>
    <Network ovf:name="NAT">
      <Description>Logical network used by this appliance.</Description>
    </Network>
  </NetworkSection>
  <VirtualSystem ovf:id="librenms-ubuntu-18.04-amd64">
    <Info>A virtual machine</Info>
    <ProductSection>
      <Info>Meta-information about the installed software</Info>
      <Product>LibreNMS</Product>
      <Version>LibreNMS</Version>
      <ProductUrl>https://www.librenms.org</ProductUrl>
    </ProductSection>
    <AnnotationSection>
      <Info>A human-readable annotation</Info>
      <Annotation>LibreNMS, a fully featured network monitoring system that provides a wealth of features and device support.</Annotation>
    </AnnotationSection>
    <OperatingSystemSection ovf:id="94">
      <Info>The kind of installed guest operating system</Info>
      <Description>Ubuntu_64</Description>
      <vbox:OSType ovf:required="false">Ubuntu_64</vbox:OSType>
    </OperatingSystemSection>
    <VirtualHardwareSection>
      <Info>Virtual hardware requirements for a virtual machine</Info>
      <System>
        <vssd:ElementName>Virtual Hardware Family</vssd:ElementName>
        <vssd:InstanceID>0</vssd:InstanceID>
        <vssd:VirtualSystemIdentifier>librenms-ubuntu-18.04-amd64</vssd:VirtualSystemIdentifier>
        <vssd:VirtualSystemType>vmx-14</vssd:VirtualSystemType>
      </System>
      <Item>
        <rasd:Caption>1 virtual CPU</rasd:Caption>
        <rasd:Description>Number of virtual CPUs</rasd:Description>
        <rasd:ElementName>1 virtual CPU</rasd:ElementName>
        <rasd:InstanceID>1</rasd:InstanceID>
        <rasd:ResourceType>3</rasd:ResourceType>
        <rasd:VirtualQuantity>1</rasd:VirtualQuantity>
      </Item>
      <Item>
        <rasd:AllocationUnits>MegaBytes</rasd:AllocationUnits>
        <rasd:Caption>512 MB of memory</rasd:Caption>
        <rasd:Description>Memory Size</rasd:Description>
        <rasd:ElementName>512 MB of memory</rasd:ElementName>
        <rasd:InstanceID>2</rasd:InstanceID>
        <rasd:ResourceType>4</rasd:ResourceType>
        <rasd:VirtualQuantity>512</rasd:VirtualQuantity>
      </Item>
      <Item>
        <rasd:Address>0</rasd:Address>
        <rasd:Caption>SCSIController</rasd:Caption>
        <rasd:Description>SCSI Controller</rasd:Description>
        <rasd:ElementName>SCSIController</rasd:ElementName>
        <rasd:InstanceID>3</rasd:InstanceID>
        <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType>
        <rasd:ResourceType>6</rasd:ResourceType>
      </Item>
      <Item>
        <rasd:Address>1</rasd:Address>
        <rasd:Caption>SCSIController</rasd:Caption>
        <rasd:Description>SCSI Controller</rasd:Description>
        <rasd:ElementName>SCSIController</rasd:ElementName>
        <rasd:InstanceID>4</rasd:InstanceID>
        <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType>
        <rasd:ResourceType>6</rasd:ResourceType>
      </Item>
      <Item>
        <rasd:AddressOnParent>0</rasd:AddressOnParent>
        <rasd:Caption>disk1</rasd:Caption>
        <rasd:Description>Disk Image</rasd:Description>
        <rasd:ElementName>disk1</rasd:ElementName>
        <rasd:HostResource>/disk/vmdisk1</rasd:HostResource>
        <rasd:InstanceID>5</rasd:InstanceID>
        <rasd:Parent>3</rasd:Parent>
        <rasd:ResourceType>17</rasd:ResourceType>
      </Item>
      <Item>
        <rasd:AutomaticAllocation>true</rasd:AutomaticAllocation>
        <rasd:Caption>Ethernet adapter on 'NAT'</rasd:Caption>
        <rasd:Connection>NAT</rasd:Connection>
        <rasd:ElementName>Ethernet adapter on 'NAT'</rasd:ElementName>
        <rasd:InstanceID>6</rasd:InstanceID>
        <rasd:ResourceSubType>E1000</rasd:ResourceSubType>
        <rasd:ResourceType>10</rasd:ResourceType>
      </Item>
    </VirtualHardwareSection>
    <vbox:Machine ovf:required="false" version="1.16-linux" uuid="{d13ce742-c55f-4e66-af89-642e02e8e190}" name="librenms-ubuntu-18.04-amd64" OSType="Ubuntu_64" snapshotFolder="Snapshots" lastStateChange="2020-04-28T05:01:10Z">
      <ovf:Info>Complete VirtualBox machine configuration in VirtualBox format</ovf:Info>
      <Hardware>
        <CPU>
          <PAE enabled="true"/>
          <LongMode enabled="true"/>
          <X2APIC enabled="true"/>
          <HardwareVirtExLargePages enabled="false"/>
        </CPU>
        <Memory RAMSize="512"/>
        <Boot>
          <Order position="1" device="HardDisk"/>
          <Order position="2" device="DVD"/>
          <Order position="3" device="None"/>
          <Order position="4" device="None"/>
        </Boot>
        <Display VRAMSize="12"/>
        <RemoteDisplay>
          <VRDEProperties>
            <Property name="TCP/Address" value="127.0.0.1"/>
            <Property name="TCP/Ports" value="5922"/>
          </VRDEProperties>
        </RemoteDisplay>
        <BIOS>
          <IOAPIC enabled="true"/>
        </BIOS>
        <Network>
          <Adapter slot="0" enabled="true" MACAddress="080027CCD773" type="82540EM">
            <NAT>
              <Forwarding name="http" proto="1" hostport="8080" guestport="80"/>
              <Forwarding name="ssh" proto="1" hostport="2023" guestport="22"/>
            </NAT>
          </Adapter>
        </Network>
        <AudioAdapter driver="ALSA" enabledIn="false" enabledOut="false"/>
      </Hardware>
      <StorageControllers>
        <StorageController name="SCSI Controller" type="lsilogic" PortCount="2" useHostIOCache="true" Bootable="true">
          <AttachedDevice type="HardDisk" hotpluggable="false" port="0" device="0">
            <Image uuid="{c35661a3-9696-4a98-a1a2-d7407388171e}"/>
          </AttachedDevice>
        </StorageController>
      </StorageControllers>
    </vbox:Machine>
  </VirtualSystem>
</Envelope>
`

**Comment by hadrins** [comment]
After spending most of the day working on this.  I have had no luck.  Perhaps I will try the pastebin info above.    SO after trying to get his to import into VMWare ESXi. I downloaded and install Virtual Box.   On the Ubuntu VM I just get a core dump,  and on the CentOS after import I get a message no boot device.   Not having much luck with the manual install either.

**Comment by hadrins** [comment]
> The following OVF worked for me. I then imported the ovf and vmdk ignoring the mf file.
> 
> Or for better formatting via pastebin:
> https://pastebin.com/r3wCx8v1
> 
> `<?xml version="1.0"?> <Envelope ovf:version="1.0" xml:lang="en-US" xmlns="http://schemas.dmtf.org/ovf/envelope/1" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:vbox="http://www.virtualbox.org/ovf/machine"> <References> <File ovf:id="file1" ovf:href="librenms-ubuntu-18.04-amd64-disk001.vmdk"/> </References> <DiskSection> <Info>List of the virtual disks used in the package</Info> <Disk ovf:capacity="42949672960" ovf:diskId="vmdisk1" ovf:fileRef="file1" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized" vbox:uuid="c35661a3-9696-4a98-a1a2-d7407388171e"/> </DiskSection> <NetworkSection> <Info>Logical networks used in the package</Info> <Network ovf:name="NAT"> <Description>Logical network used by this appliance.</Description> </Network> </NetworkSection> <VirtualSystem ovf:id="librenms-ubuntu-18.04-amd64"> <Info>A virtual machine</Info> <ProductSection> <Info>Meta-information about the installed software</Info> <Product>LibreNMS</Product> <Version>LibreNMS</Version> <ProductUrl>https://www.librenms.org</ProductUrl> </ProductSection> <AnnotationSection> <Info>A human-readable annotation</Info> <Annotation>LibreNMS, a fully featured network monitoring system that provides a wealth of features and device support.</Annotation> </AnnotationSection> <OperatingSystemSection ovf:id="94"> <Info>The kind of installed guest operating system</Info> <Description>Ubuntu_64</Description> <vbox:OSType ovf:required="false">Ubuntu_64</vbox:OSType> </OperatingSystemSection> <VirtualHardwareSection> <Info>Virtual hardware requirements for a virtual machine</Info> <System> <vssd:ElementName>Virtual Hardware Family</vssd:ElementName> <vssd:InstanceID>0</vssd:InstanceID> <vssd:VirtualSystemIdentifier>librenms-ubuntu-18.04-amd64</vssd:VirtualSystemIdentifier> <vssd:VirtualSystemType>vmx-14</vssd:VirtualSystemType> </System> <Item> <rasd:Caption>1 virtual CPU</rasd:Caption> <rasd:Description>Number of virtual CPUs</rasd:Description> <rasd:ElementName>1 virtual CPU</rasd:ElementName> <rasd:InstanceID>1</rasd:InstanceID> <rasd:ResourceType>3</rasd:ResourceType> <rasd:VirtualQuantity>1</rasd:VirtualQuantity> </Item> <Item> <rasd:AllocationUnits>MegaBytes</rasd:AllocationUnits> <rasd:Caption>512 MB of memory</rasd:Caption> <rasd:Description>Memory Size</rasd:Description> <rasd:ElementName>512 MB of memory</rasd:ElementName> <rasd:InstanceID>2</rasd:InstanceID> <rasd:ResourceType>4</rasd:ResourceType> <rasd:VirtualQuantity>512</rasd:VirtualQuantity> </Item> <Item> <rasd:Address>0</rasd:Address> <rasd:Caption>SCSIController</rasd:Caption> <rasd:Description>SCSI Controller</rasd:Description> <rasd:ElementName>SCSIController</rasd:ElementName> <rasd:InstanceID>3</rasd:InstanceID> <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType> <rasd:ResourceType>6</rasd:ResourceType> </Item> <Item> <rasd:Address>1</rasd:Address> <rasd:Caption>SCSIController</rasd:Caption> <rasd:Description>SCSI Controller</rasd:Description> <rasd:ElementName>SCSIController</rasd:ElementName> <rasd:InstanceID>4</rasd:InstanceID> <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType> <rasd:ResourceType>6</rasd:ResourceType> </Item> <Item> <rasd:AddressOnParent>0</rasd:AddressOnParent> <rasd:Caption>disk1</rasd:Caption> <rasd:Description>Disk Image</rasd:Description> <rasd:ElementName>disk1</rasd:ElementName> <rasd:HostResource>/disk/vmdisk1</rasd:HostResource> <rasd:InstanceID>5</rasd:InstanceID> <rasd:Parent>3</rasd:Parent> <rasd:ResourceType>17</rasd:ResourceType> </Item> <Item> <rasd:AutomaticAllocation>true</rasd:AutomaticAllocation> <rasd:Caption>Ethernet adapter on 'NAT'</rasd:Caption> <rasd:Connection>NAT</rasd:Connection> <rasd:ElementName>Ethernet adapter on 'NAT'</rasd:ElementName> <rasd:InstanceID>6</rasd:InstanceID> <rasd:ResourceSubType>E1000</rasd:ResourceSubType> <rasd:ResourceType>10</rasd:ResourceType> </Item> </VirtualHardwareSection> <vbox:Machine ovf:required="false" version="1.16-linux" uuid="{d13ce742-c55f-4e66-af89-642e02e8e190}" name="librenms-ubuntu-18.04-amd64" OSType="Ubuntu_64" snapshotFolder="Snapshots" lastStateChange="2020-04-28T05:01:10Z"> <ovf:Info>Complete VirtualBox machine configuration in VirtualBox format</ovf:Info> <Hardware> <CPU> <PAE enabled="true"/> <LongMode enabled="true"/> <X2APIC enabled="true"/> <HardwareVirtExLargePages enabled="false"/> </CPU> <Memory RAMSize="512"/> <Boot> <Order position="1" device="HardDisk"/> <Order position="2" device="DVD"/> <Order position="3" device="None"/> <Order position="4" device="None"/> </Boot> <Display VRAMSize="12"/> <RemoteDisplay> <VRDEProperties> <Property name="TCP/Address" value="127.0.0.1"/> <Property name="TCP/Ports" value="5922"/> </VRDEProperties> </RemoteDisplay> <BIOS> <IOAPIC enabled="true"/> </BIOS> <Network> <Adapter slot="0" enabled="true" MACAddress="080027CCD773" type="82540EM"> <NAT> <Forwarding name="http" proto="1" hostport="8080" guestport="80"/> <Forwarding name="ssh" proto="1" hostport="2023" guestport="22"/> </NAT> </Adapter> </Network> <AudioAdapter driver="ALSA" enabledIn="false" enabledOut="false"/> </Hardware> <StorageControllers> <StorageController name="SCSI Controller" type="lsilogic" PortCount="2" useHostIOCache="true" Bootable="true"> <AttachedDevice type="HardDisk" hotpluggable="false" port="0" device="0"> <Image uuid="{c35661a3-9696-4a98-a1a2-d7407388171e}"/> </AttachedDevice> </StorageController> </StorageControllers> </vbox:Machine> </VirtualSystem> </Envelope> `

Worked for me!!!!  Thanks.    I just had to change the network device from the enp to ens160.

**Comment by murrant** [comment]
Would love to see an OVA build for vmware, but it doesn't seem that easy.
