### ISSUE TITLE
in v1.56 of the CentOS build, rebooting waits 5 minutes to shut down MariaDB

### ISSUE THREAD

**Issue by Chewie9999** [librenms/packer-builds#13]
For some reason, when I reboot my VM, i get the message "A stop job is running for MariaDB database server" with a timeout period of 5 minutes.
All I have done since installation is do the following:
`yum check-update`
`sudo yum update` which installed the following:
```
epel-release-7-11.noarc
jwhois-4.0-45.el7.x86_64
php-justinrainbow-json-schema5-5.2.8-1.el7.noarch
```
`./daily.php`

./validate.php reports the following:
```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.56
DB Schema | 2019_09_05_153524_create_notifications_attribs_index (141)
PHP       | 7.2.22
MySQL     | 5.5.64-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 1.9.0
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[FAIL]  MySQL Database collation is wrong: latin1 latin1_swedish_ci
        [FIX]: 
        Check https://t.libren.ms/-zdwk for info on how to fix.
[OK]    Database schema correct
[FAIL]  The poller (localhost.localdomain) has not completed within the last 5 minutes, check the cron job.
[FAIL]  Discovery has not completed in the last 24 hours.
        [FIX]: 
        Check the cron job to make sure it is running and using discovery-wrapper.py
```

The link mentioned for the fix does not work.
The last FAIL for cron can be ignored as I have only been running the VM for an hour.

**Comment by laf** [comment]
This may not be an issue with the builds so I'm going to close this. You'll need to just do some general checking in to with MariaDB isn't shutting down, check the logs.

Feel free to post on the community forums for further help.

**Comment by Chewie9999** [comment]
Agreed, I think is was just temporary. Further reboots have been ok. Maybe I was being impatient!
