### ISSUE TITLE
Not clear how this is updated

### ISSUE THREAD

**Issue by supersexy** [librenms/packer-builds#17]
It is nont clear how the LibreNMS installations will update - please document that, thanks. (apt / some other mechanism / manual intervention needed?)

**Comment by murrant** [comment]
This is just a pre-built VM.  It is the same as a standard build except you have less control on how it is set up.  Check the standard docs https://docs.librenms.org

**Comment by supersexy** [comment]
You did not answer my question - I was asking about the update mechanism - I can see that it is a VM and  can see that it is pre-built. Again, in different words to make me better understandable: how does the installed software in the VM update? Will it update at all? Will it need manual intervention to be updated? Is there some kind of automatic updates going on, e.g. via standard operating system packaging system? This is important to know and should be documented for the VM.

**Comment by TheGreatDoc** [comment]
@supersexy As @murrant said, its just like a standard installation.

In the moment you bring up the VM with internet connection, it will daily update without any issue.
