### ISSUE TITLE
Root Password on shell

### ISSUE THREAD

**Issue by mwasim82** [librenms/packer-builds#18]
i want to login to Ubuntu 18.04.3 what will b the root password
Given passowrd on the websites are not working

**Comment by TheGreatDoc** [comment]
In ubuntu, there is no root password.

If you want to go root, just `sudo su -` and enter the librenms passwd

**Comment by mwasim82** [comment]
sorry i am not able to login with any user to get to sudo su 
![Capture](https://user-images.githubusercontent.com/59739976/72167943-f2ae5b00-33ed-11ea-945e-ce44f4d09524.JPG)

librenms 
Credentials

    SSH
    username: librenms
    password: CDne3fwdfds
    MySQL/MariaDB
    username: librenms
    password: D42nf23rewD
    WebUI
    username: librenms
    password: D32fwefwef

not working for me

**Comment by TheGreatDoc** [comment]
https://docs.librenms.org/Installation/Images/#credentials

```
username: librenms
password: CDne3fwdfds
```

**Comment by mwasim82** [comment]
> not working for me

**Comment by TheGreatDoc** [comment]
I cant test it right now but Im pretty sure passwords are correct.

Let me try to reach someone who can test it.

**Comment by DutchBusiness** [comment]
Downloaded latest OVA, installed & tested, username and password are correct.
![preview](https://user-images.githubusercontent.com/60257199/73065639-55026380-3ea4-11ea-933f-96bb609482e7.png)

**Comment by adamh98** [comment]
I've been encountering the same thing with failed login. I've never been able to get everything to work 100%, but now I'm trying to work through the errors. 
![image](https://user-images.githubusercontent.com/25110731/77384191-fa6d7280-6d41-11ea-8f06-5c5a713529e3.png)

**Comment by sdrenner** [comment]
Did you all ever figure out the PW? i have copy and pasted the PW and still no luck.

**Comment by DutchBusiness** [comment]
As mentioned in the other comments:

```
SSH
username: librenms
password: CDne3fwdfds
MySQL/MariaDB
username: librenms
password: D42nf23rewD
WebUI
username: librenms
password: D32fwefwef
```

No difficulties other then yours (seems to me)
Check your keyboard and capslock, a simple copy and paste will help (when using putty e.g)

Regards,
Ronald

**Comment by murrant** [comment]
`sudo passwd root` will allow you to update the root password.
