### ISSUE TITLE
What image formats do we want to support

### ISSUE THREAD

**Issue by laf** [librenms/packer-builds#2]
https://www.packer.io/docs/builders/index.html

Some simple ones could be like qemu.

VMWare requires an ESXi box to work.

**Comment by TheGreatDoc** [comment]
Maybe a poll in the community forum? 

VMWare is going to be the one of most used. Maybe we could virtualize an EXSi inside virtualbox?

**Comment by includes08** [comment]
Line 35: Unsupported hardware family 'virtualbox-2.2'

can you guys solve this.

thanks in advance :) we esxi users would love it it works ;D

**Comment by rdiez** [comment]
A small company is not going to get involved with VMWare / ESXi.

VirtualBox does not seem suitable for running unattended as a service.

I would say that the libvirt/KVM/Qemu combination would be the most popular.

The "Virtual Machine Manager" (virt-manager) provides a reasonable GUI for "normal" admins, and is available in the standard Ubuntu and RedHat repositories.

**Comment by murrant** [comment]
Fixed by #35
