### ISSUE TITLE
new image with php7.4?

### ISSUE THREAD

**Issue by Kampfwurst** [librenms/packer-builds#20]
Hi,

In this image i get this error.

"Warning: PHP version 7.3 is the minimum supported version as of November, 2020. We recommend you update PHP to a supported version (7.4 suggested) to continue to receive updates. If you do not update PHP, LibreNMS will continue to function but stop receiving bug fixes and updates."

is there a new image?

**Comment by Cheeze-It** [comment]
I have figured out that there's a somewhat easy workaround for this. First one goes and removes via apt php7.2 and installs php7.4.

Then one must go to /etc/nginx/conf.d/librenms.conf and change the following:

fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
to
fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;

Then restarts:

systemctl restart nginx
systemctl restart php7.4-fpm

It works :) 

However if one does an update then they'll have to go here if one wants to properly update:

https://community.librenms.org/t/undefined-index-name-in-packagemanifest-php-line-122/13996/8


Then it works to be able to update to latest.
