### ISSUE TITLE
Fail: MySQL tables collation is wrong &  MySQL column collation is wrong

### ISSUE THREAD

**Issue by sendtomelvin** [librenms/packer-builds#23]
====================================
Component | Version
--------- | -------
LibreNMS  | 21.2.0-23-g0a8f24c5b
DB Schema | 2021_02_09_122930_migrate_to_utf8mb4 (201)
PHP       | 7.4.9
Python    | 3.8.6
MySQL     | 10.3.25-MariaDB-0ubuntu1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.0.11
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[WARN]  Your database schema has extra migrations (2021_02_09_122930_migrate_to_utf8mb4). If you just switched to the stable release from the daily release, your database is in between releases and this will be resolved with the next release.
[FAIL]  MySQL tables collation is wrong: 
	[FIX]: 
	Check http://bit.ly/2lAG9H8 for info on how to fix.
	Tables:
	 mpls_sdps utf8mb4 utf8mb4_unicode_ci
	 entPhysical_state utf8mb4 utf8mb4_unicode_ci
	 session utf8mb4 utf8mb4_unicode_ci
	 mpls_lsp_paths utf8mb4 utf8mb4_unicode_ci
	 pdb_ix utf8mb4 utf8mb4_unicode_ci
	 proxmox utf8mb4 utf8mb4_unicode_ci
	 component utf8mb4 utf8mb4_unicode_ci
	 mac_accounting utf8mb4 utf8mb4_unicode_ci
	 syslog utf8mb4 utf8mb4_unicode_ci
	 netscaler_vservers utf8mb4 utf8mb4_unicode_ci
	 tnmsneinfo utf8mb4 utf8mb4_unicode_ci
	 alerts utf8mb4 utf8mb4_unicode_ci
	 plugins utf8mb4 utf8mb4_unicode_ci
	 alert_transports utf8mb4 utf8mb4_unicode_ci
	 loadbalancer_vservers utf8mb4 utf8mb4_unicode_ci
	  and 120 more...
[FAIL]  MySQL column collation is wrong: 
	[FIX]: 
	Check https://t.libren.ms/-zdwk for info on how to fix.
	Columns:
	 mpls_sdps sdpRowStatus utf8mb4 utf8mb4_unicode_ci
	 mpls_sdps sdpDelivery utf8mb4 utf8mb4_unicode_ci
	 mpls_sdps sdpDescription utf8mb4 utf8mb4_unicode_ci
	 mpls_sdps sdpAdminStatus utf8mb4 utf8mb4_unicode_ci
	 mpls_sdps sdpOperStatus utf8mb4 utf8mb4_unicode_ci
	 mpls_sdps sdpActiveLspType utf8mb4 utf8mb4_unicode_ci
	 mpls_sdps sdpFarEndInetAddressType utf8mb4 utf8mb4_unicode_ci
	 mpls_sdps sdpFarEndInetAddress utf8mb4 utf8mb4_unicode_ci
	 entPhysical_state entPhysicalIndex utf8mb4 utf8mb4_unicode_ci
	 entPhysical_state subindex utf8mb4 utf8mb4_unicode_ci
	 entPhysical_state group utf8mb4 utf8mb4_unicode_ci
	 entPhysical_state key utf8mb4 utf8mb4_unicode_ci
	 entPhysical_state value utf8mb4 utf8mb4_unicode_ci
	 session session_username utf8mb4 utf8mb4_unicode_ci
	 session session_value utf8mb4 utf8mb4_unicode_ci
	  and 493 more...
[OK]    Database schema correct

@murrant please guide me

**Comment by sendtomelvin** [comment]
@murrant

**Comment by murrant** [comment]
Database in the vm image is too old.
