### ISSUE TITLE
The provided manifest file is invalid: Invalid OVF checksum algorithm: SHA1

### ISSUE THREAD

**Issue by scaleoutsean** [librenms/packer-builds#30]
OVA librenms-ubuntu-20.04-amd64.ova from https://github.com/librenms/packer-builds/releases/tag/21.2.0 can't pass validation on vSphere 7: `The provided manifest file is invalid: Invalid OVF checksum algorithm: SHA1`

**Comment by kollnoh** [comment]
Same here.

**Comment by yolgezerahmet** [comment]
Same problem...

**Comment by nickolas1969** [comment]
Me too.

**Comment by murrant** [comment]
How is it supposed to work for vSphere if the image is built for VirtualBox?

**Comment by scaleoutsean** [comment]
Why? OVF isn't a VMware-only format.

> Oracle VM VirtualBox can import and export virtual machines in the following formats:
> - Open Virtualization Format (OVF). This is the industry-standard format. See Section 1.14.1, “About the OVF Format”.
https://docs.oracle.com/en/virtualization/virtualbox/6.0/user/ovf.html

**Comment by scaleoutsean** [comment]
Isn't OVF the industry standard format?

**Comment by murrant** [comment]
Yes, but the vm definitions inside are not always compatible.

https://www.virtualbox.org/ticket/11160
https://www.virtualbox.org/ticket/7982

**Comment by scaleoutsean** [comment]
Then I would suggest to improve README.md to say that the created image is VB-only. 

It does state that VB is a requirement but for what? To build or to import or both? 
If it's known that the resulting image is limited in such a way due to known bugs, why not state that up front?

**Comment by spastro** [comment]
Ah, okay so so not compatible vsphere....

**Comment by murrant** [comment]
Fixed by #35
