### ISSUE TITLE
Cannot Import Ubuntu 20.04 OVA into ESXI 7.0.2

### ISSUE THREAD

**Issue by bitking** [librenms/packer-builds#31]
Hi all,

When importing the OVA into ESXI 7.0.2 i get the error message "Missing child element 'Virtualhardwaresection'"

Preventing me to import the file.

Any tips on how to make this work?

**Comment by murrant** [comment]
Best way is to extract the disk, create a new vm in ESXi and then attach the disk.  The OVA is built with VirtualBox for VirtualBox.  It does not work in VMware.
