### ISSUE TITLE
VM is PHP 7 while master is on 8.1

### ISSUE THREAD

**Issue by jerji** [librenms/packer-builds#33]
The VM available here only supports PHP 7. I have tried building the images myself for php 8.1 but the VM created by packer does not complete installation even after adjusting the delays. it gets stuck at "Reached target host and network name lookups"

These scripts should be updated to the latest PHP

**Comment by murrant** [comment]
Indeed the vms are in poor shape.  No one has taken ownership of them and they don't work with VMWare.  It might be better to just remove them.

**Comment by jerji** [comment]
I don't necessarily agree that they need to absolutely work with vmware to be useful. They are very useful for people like me who are developing small things for the LibreNMS project where I don't have the ressources to run a complete instance all the time and it's very practical to just be able to start a new instance in less than 10 minutes.

**Comment by murrant** [comment]
As I said though, it seems like no one is going to update them unless someone volunteers.

**Comment by murrant** [comment]
Fixed by #35
