### ISSUE TITLE
 librenms-ubuntu-22.04-amd64-virtualbox.ova  - possible security issue

### ISSUE THREAD

**Issue by zs1rcm** [librenms/packer-builds#37]
In this ova: librenms-ubuntu-22.04-amd64-virtualbox.ova 

Our security software detected the vagrant account with password set to vagrant

**Comment by arashmohebbati** [comment]
![image](https://github.com/librenms/packer-builds/assets/117598765/030d8f25-8759-4de1-a5dc-ebdcf29af1fc)
What is the default username and password?

**Comment by sgtallenusa** [comment]
there appears to be a breach in these. a few seconds after initialization all pings appear to be hijacked/redirected and DNS points to 77980.bodis.com

**Comment by laf** [comment]
The files I uploaded haven't been changed since they were put on to GitHub, the images were built cleanly by myself and I'm pretty sure they aren't breached.
